import { loadEnv, defineConfig } from "@medusajs/framework/utils"

loadEnv(process.env.NODE_ENV || "development", process.cwd())

module.exports = defineConfig({
  projectConfig: {
    databaseUrl: process.env.DATABASE_URL,
    http: {
      storeCors: process.env.STORE_CORS!,
      adminCors: process.env.ADMIN_CORS!,
      authCors: process.env.AUTH_CORS!,
      jwtSecret: process.env.JWT_SECRET || "supersecret",
      cookieSecret: process.env.COOKIE_SECRET || "supersecret",
    },
  },
  plugins: [
    {
      resolve: "@medusajs/admin",
      options: {
        serve: true,
        autoRebuild: true,
        path: "/app",
      },
    },
  ],
  modules: [
    {
      resolve: "./src/modules/meilisearch",
      options: {
        config: {
          host: process.env.MEILISEARCH_HOST || "http://localhost:7700",
          apiKey: process.env.MEILISEARCH_API_KEY || "masterKey",
        },
        settings: {
          products: {
            type: "products",
            enabled: true,
            fields: [
              // Индексация нужных полей
              "id",
              "title",
              "subtitle",
              "description",
              "handle",
              "is_giftcard",
              "discountable",
              "thumbnail",
              "collection_id",
              "type_id",
              "weight",
              "length",
              "height",
              "width",
              "hs_code",
              "origin_country",
              "mid_code",
              "material",
              "created_at",
              "updated_at",
              "options",
              "tags",
              "images",
              "variants",
              "metadata",
              "minPrice",
            ],
            indexSettings: {
              searchableAttributes: [
                "title",
                "description",
                "handle",
                "variants.sku",
                "variants.title",
                "options.title",
                "options.values.value",
              ],
              displayedAttributes: [
                "id",
                "title",
                "subtitle",
                "description",
                "handle",
                "is_giftcard",
                "discountable",
                "thumbnail",
                "collection_id",
                "type_id",
                "weight",
                "length",
                "height",
                "width",
                "hs_code",
                "origin_country",
                "mid_code",
                "material",
                "created_at",
                "updated_at",
                "options",
                "tags",
                "images",
                "variants",
                "metadata",
                "minPrice",
              ],
              filterableAttributes: [
                "id",
                "handle",
                "region_id",
                "variants.calculated_price",
                "variants.inventory_quantity",
                "options.title",
                "options.values.value",
                "minPrice",
              ],
              sortableAttributes: [
                "title",
                "created_at",
                "variants.calculated_price",
                "variants.inventory_quantity",
                "minPrice",
              ],
            },
            primaryKey: "id",
          },
        },
      },
    },
  ],
})
